In [58]:
import pandas as pd
import numpy as np

In [2]:
People = []
passions = []

In [3]:
gender_options = ['Male','Female','Other']
hair_color_options = ['Brown','Blond','Black','Blue','White','Red','Mixed','Other']
hair_texture_options = ['Straight','Wavy','Curly','Frizzy','Other']
eye_color_options = ['Brown','Blue','Red','Amber','Gray','Green','Hazel','Mixed','Other']

gender_seeking_options = ['Male','Female','Other','Unimportant']
hair_color_seeking_options = ['Brown','Blond','Black','Blue','White','Red','Mixed','Other','Unimportant']
hair_texture_seeking_options = ['Straight','Wavy','Curly','Frizzy','Other','Unimportant']
eye_color_seeking_options = ['Brown','Blue','Red','Amber','Gray','Green','Hazel','Mixed','Other','Unimportant']

columns = ['Characteristic_age','Characteristic_Eye_Color','Characterisic_Gender','Characteristic_Hair_Texture','Characteristic_Hair_Color','Characteristic_Height','Characteristic_Passions','Name','Number','Seeking_Age_Max','Seeking_Age_Min','Seeking_Eye_Color','Seeking_Gender','Seeking_Hair_Color','Seeking_Hair_Texture','Seeking_Height']

In [21]:
name = input("Enter your full name: ")
number = input("Enter your contact phone number: ")

while True:
    age = input('Enter your age: ')
    try:
        if int(age) >= 16 and int(age) < 100:
            break
        else:
            print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
    except ValueError:
        print("\nNot a Valid Input, Please Enter a Number Between 16 and 99.\n")

while True:
    gender = input('Enter your gender: ')
    if gender.capitalize() in gender_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter 'Male', 'Female', or 'Other'.\n")

while True:
    hair_color = input('Enter your hair color: ')
    if hair_color.capitalize() in hair_color_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_color_options)

while True:
    hair_texture = input('Enter your hair texture: ')
    if hair_texture.capitalize() in hair_texture_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_texture_options)

while True:
    eye_color = input('Enter your eye color: ')
    if eye_color.capitalize() in eye_color_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",eye_color_options)

while True:
    height = input('Enter your height (in inches, 5ft = 60in): ')
    try:
        if int(height) >= 48 and int(age) < 96:
            break
        else:
            print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96.\n")
    except ValueError:
        print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96.\n")

while True:
    passion = input("Enter your passions/interests/hobbies, 1 by 1. Type 'Done' when you are finished: ")
    if passion.capitalize() == 'Done':
        print("\nFinished!\n")
        break
    else:
        passions.append(passion.capitalize())

while True:
    age_min_seeking = input("Enter your partners desired MINumum age, or type 'Unimportant': ") 
    if age_min_seeking.capitalize() != 'Unimportant':
        try:
            if int(age_min_seeking) >= 16 and int(age_min_seeking) < 100:
                break
            else:
                print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
        except ValueError:
            print("\nNot a Valid Input, Please Enter a Number Between 16 and 99.\n")
    else:
        break

while True:
    age_max_seeking = input("Enter your partners desired MAXimum age, or type 'Unimportant': ")
    if age_max_seeking.capitalize() != 'Unimportant':
        try:
            if int(age_max_seeking) >= 16 and int(age_max_seeking) < 100:
                if (int(age_max_seeking) - int(age_min_seeking)) > -1:
                    break
                else:
                    print("\nNot a Valid Input, Please Make Sure This Value Is Equal to Or Larger Than Your Partners Desired Minimum Age.\n")
            else:
                print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
        except ValueError:
            print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
    else:
        break

while True:
    gender_seeking = input("Enter your partners desired gender, or type 'Unimportant': ")
    if gender_seeking.capitalize() == "Unimportant":
        break
    else:
        if gender_seeking.capitalize() in gender_seeking_options:
            break
        else:
            print("\nNot a Valid Input, Please Enter 'Male', 'Female', 'Other', or 'Unimportant'.\n")

while True:
    hair_color_seeking = input("Enter your partners desired hair color, or type 'Unimportant': ")
    if hair_color_seeking.capitalize() in hair_color_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_color_seeking_options)

while True:
    hair_texture_seeking = input("Enter your partners desired hair texture, or type 'Unimportant': ")
    if hair_texture_seeking.capitalize() in hair_texture_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_texture_seeking_options)

while True:
    eye_color_seeking = input("Enter your partners desired eye color, or type 'Unimportant': ")
    if eye_color_seeking.capitalize() in eye_color_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",eye_color_seeking_options)

while True:
    height_seeking = input("Enter your partners desired height (in inches, 5ft = 60in), or type 'Unimportant': ")
    if height_seeking.capitalize() == 'Unimportant':
        break
    else:
        try:
            if int(height_seeking) >= 48 and int(height_seeking) < 96:
                break
            else:
                print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96, or 'Unimportant'.\n")
        except ValueError:
            print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96, or 'Unimportant'.\n")

People.append({
    'Name': name,
    'Number': number,

    'Characteristic_Age': age.capitalize(),
    'Characteristic_Gender': gender.capitalize(),
    'Characteristic_Hair_color': hair_color.capitalize(),
    'Characteristic_Hair_Texture': hair_texture.capitalize(),
    'Characteristic_Eye_Color': eye_color.capitalize(),
    'Characteristic_Height': height.capitalize(),
    'Characteristic_Passions': passions,

    'Seeking_Age_Min': age_min_seeking.capitalize(),
    'Seeking_Age_Max': age_max_seeking.capitalize(),
    'Seeking_Gender': gender_seeking.capitalize(),
    'Seeking_Hair_Color': hair_color_seeking.capitalize(),
    'Seeking_Hair_Texture': hair_texture_seeking.capitalize(),
    'Seeking_Eye_Color': eye_color_seeking.capitalize(),
    'Seeking_Height': height_seeking.capitalize()
})

pd.DataFrame(People)
df = pd.DataFrame(People)
df.to_csv('People.csv')

print("\nInformation Successfully Inputted! \n")

Enter your full name: princess dianna
Enter your contact phone number: 6786786677
Enter your age: 63
Enter your gender: female
Enter your hair color: blonde

Not a Valid Input, Please Enter a Value From The Following Options:
 ['Brown', 'Blond', 'Black', 'Blue', 'White', 'Red', 'Mixed', 'Other']
Enter your hair color: blond
Enter your hair texture: curly
Enter your eye color: blue
Enter your height (in inches, 5ft = 60in): 64
Enter your passions/interests/hobbies, 1 by 1. Type 'Done' when you are finished: being princess
Enter your passions/interests/hobbies, 1 by 1. Type 'Done' when you are finished: done

Finished!

Enter your partners desired MINumum age, or type 'Unimportant': 22
Enter your partners desired MAXimum age, or type 'Unimportant': 67
Enter your partners desired gender, or type 'Unimportant': male
Enter your partners desired hair color, or type 'Unimportant': brown
Enter your partners desired hair texture, or type 'Unimportant': blonde

Not a Valid Input, Please Enter a Value From The Following Options:
 ['Straight', 'Wavy', 'Curly', 'Frizzy', 'Other', 'Unimportant']
Enter your partners desired hair texture, or type 'Unimportant': curly
Enter your partners desired eye color, or type 'Unimportant': blond

Not a Valid Input, Please Enter a Value From The Following Options:
 ['Brown', 'Blue', 'Red', 'Amber', 'Gray', 'Green', 'Hazel', 'Mixed', 'Other', 'Unimportant']
Enter your partners desired eye color, or type 'Unimportant': gray
Enter your partners desired height (in inches, 5ft = 60in), or type 'Unimportant': 66

Information Successfully Inputted!

In [25]:
pd.DataFrame(People)
df = pd.DataFrame(People)
df.to_csv('People.csv')

info = pd.read_csv('People.csv')
info

,Unnamed: 0,Characteristic_Age,Characteristic_Eye_Color,Characteristic_Gender,Characteristic_Hair_Texture,Characteristic_Hair_color,Characteristic_Height,Characteristic_Passions,Name,Number,Seeking_Age_Max,Seeking_Age_Min,Seeking_Eye_Color,Seeking_Gender,Seeking_Hair_Color,Seeking_Hair_Texture,Seeking_Height
0,0,20,Brown,Male,Straight,Brown,72,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",Ian Orlando,8022384553,22,18,Unimportant,Female,Unimportant,Unimportant,69
1,1,20,Mixed,Female,Wavy,Brown,69,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",Sarah Crawford,8022384553,22,20,Brown,Male,Brown,Straight,72
2,2,21,Blue,Male,Straight,Blond,70,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",John smith,1234567899,21,17,Unimportant,Unimportant,Unimportant,Unimportant,70
3,3,22,Red,Male,Curly,Brown,55,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",bobby columbo,iorlando@syr.edu,21,20,Brown,Female,Brown,Unimportant,Unimportant
4,4,18,Blue,Male,Straight,Blue,66,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",joseph levit,2828082108312,19,18,Blue,Male,Blue,Straight,66
5,5,63,Blue,Female,Curly,Blond,64,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",princess dianna,6786786677,67,22,Gray,Male,Brown,Curly,66

In [28]:
name = input("Enter your name: ")
person = info[ info['Name'].str.startswith(name)]
person

Enter your name: Ian

,Unnamed: 0,Characteristic_Age,Characteristic_Eye_Color,Characteristic_Gender,Characteristic_Hair_Texture,Characteristic_Hair_color,Characteristic_Height,Characteristic_Passions,Name,Number,Seeking_Age_Max,Seeking_Age_Min,Seeking_Eye_Color,Seeking_Gender,Seeking_Hair_Color,Seeking_Hair_Texture,Seeking_Height
0,0,20,Brown,Male,Straight,Brown,72,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",Ian Orlando,8022384553,22,18,Unimportant,Female,Unimportant,Unimportant,69

In [38]:
print(person['Characteristic_Age'])
print(person['Seeking_Age_Max'])
print(person['Seeking_Age_Min'])

0    20
Name: Characteristic_Age, dtype: int64
0    22
Name: Seeking_Age_Max, dtype: int64
0    18
Name: Seeking_Age_Min, dtype: int64

In [52]:
info[ info['Characteristic_Age'] == 22]

,Unnamed: 0,Characteristic_Age,Characteristic_Eye_Color,Characteristic_Gender,Characteristic_Hair_Texture,Characteristic_Hair_color,Characteristic_Height,Characteristic_Passions,Name,Number,Seeking_Age_Max,Seeking_Age_Min,Seeking_Eye_Color,Seeking_Gender,Seeking_Hair_Color,Seeking_Hair_Texture,Seeking_Height
3,3,22,Red,Male,Curly,Brown,55,"['Snowboarding', 'Skiing', 'Writing', 'Smart',...",bobby columbo,iorlando@syr.edu,21,20,Brown,Female,Brown,Unimportant,Unimportant

In [66]:
person['Seeking_Age_Max'][0]

22

In [55]:
dir(pd.core.series.Series)

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_SLICEMAP',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_prepare__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__bytes__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__unicode__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_only_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_allow_index_ops',
 '_at',
 '_binop',
 '_box_item_values',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_percentile',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_for_slice',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_expand_axes',
 '_formatting_values',
 '_from_axes',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_iat',
 '_iget_item_cache',
 '_iloc',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_cython_func',
 '_is_datelike_mixed_type',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_loc',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_axis',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_subtyp',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_setup_axes',
 '_shallow_copy',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_unpickle_series_compat',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'as_blocks',
 'as_matrix',
 'asfreq',
 'asobject',
 'asof',
 'astype',
 'at',
 'at_time',
 'autocorr',
 'axes',
 'base',
 'between',
 'between_time',
 'bfill',
 'blocks',
 'bool',
 'cat',
 'clip',
 'clip_lower',
 'clip_upper',
 'combine',
 'combine_first',
 'compound',
 'compress',
 'consolidate',
 'convert_objects',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'data',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'dropna',
 'dt',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_array',
 'from_csv',
 'ftype',
 'ftypes',
 'ge',
 'get',
 'get_dtype_counts',
 'get_ftype_counts',
 'get_value',
 'get_values',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imag',
 'index',
 'infer_objects',
 'interpolate',
 'is_copy',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'itemsize',
 'iteritems',
 'ix',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'nonzero',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'ptp',
 'put',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'real',
 'reindex',
 'reindex_axis',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'reshape',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'select',
 'sem',
 'set_axis',
 'set_value',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'sortlevel',
 'squeeze',
 'std',
 'str',
 'strides',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dense',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_msgpack',
 'to_period',
 'to_pickle',
 'to_sparse',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'tolist',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'valid',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']