In [1]:
import pandas as pd
import numpy as np

In [2]:
gender_options = ['Male','Female','Other']
hair_color_options = ['Brown','Blond','Black','Blue','White','Red','Mixed','Other']
hair_texture_options = ['Straight','Wavy','Curly','Frizzy','Other']
eye_color_options = ['Brown','Blue','Red','Amber','Gray','Green','Hazel','Mixed','Other']

gender_seeking_options = ['Male','Female','Other','Unimportant']
hair_color_seeking_options = ['Brown','Blond','Black','Blue','White','Red','Mixed','Other','Unimportant']
hair_texture_seeking_options = ['Straight','Wavy','Curly','Frizzy','Other','Unimportant']
eye_color_seeking_options = ['Brown','Blue','Red','Amber','Gray','Green','Hazel','Mixed','Other','Unimportant']

In [52]:
People = []
name = input("Enter your full name: ")
number = input("Enter your contact phone number: ")

while True:
    age = input('Enter your age: ')
    try:
        if int(age) >= 16 and int(age) < 100:
            break
        else:
            print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
    except ValueError:
        print("\nNot a Valid Input, Please Enter a Number Between 16 and 99.\n")

while True:
    gender = input('Enter your gender: ')
    if gender.capitalize() in gender_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter 'Male', 'Female', or 'Other'.\n")

while True:
    hair_color = input('Enter your hair color: ')
    if hair_color.capitalize() in hair_color_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_color_options)

while True:
    hair_texture = input('Enter your hair texture: ')
    if hair_texture.capitalize() in hair_texture_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_texture_options)

while True:
    eye_color = input('Enter your eye color: ')
    if eye_color.capitalize() in eye_color_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",eye_color_options)

while True:
    height = input('Enter your height (in inches, 5ft = 60in): ')
    try:
        if int(height) >= 48 and int(age) < 96:
            break
        else:
            print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96.\n")
    except ValueError:
        print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96.\n")

while True:
    age_min_seeking = input("Enter your partners desired MINumum age, or type 'Unimportant': ") 
    if age_min_seeking.capitalize() != 'Unimportant':
        try:
            if int(age_min_seeking) >= 16 and int(age_min_seeking) < 100:
                break
            else:
                print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
        except ValueError:
            print("\nNot a Valid Input, Please Enter a Number Between 16 and 99.\n")
    else:
        break

while True:
    age_max_seeking = input("Enter your partners desired MAXimum age, or type 'Unimportant': ")
    if age_max_seeking.capitalize() != 'Unimportant':
        try:
            if int(age_max_seeking) >= 16 and int(age_max_seeking) < 100:
                if (int(age_max_seeking) - int(age_min_seeking)) > -1:
                    break
                else:
                    print("\nNot a Valid Input, Please Make Sure This Value Is Equal to Or Larger Than Your Partners Desired Minimum Age.\n")
            else:
                print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
        except ValueError:
            print("\nNot A Valid Input, Please Enter a Number Between 16 and 99.\n")
    else:
        break

while True:
    gender_seeking = input("Enter your partners desired gender, or type 'Unimportant': ")
    if gender_seeking.capitalize() == "Unimportant":
        break
    else:
        if gender_seeking.capitalize() in gender_seeking_options:
            break
        else:
            print("\nNot a Valid Input, Please Enter 'Male', 'Female', 'Other', or 'Unimportant'.\n")

while True:
    hair_color_seeking = input("Enter your partners desired hair color, or type 'Unimportant': ")
    if hair_color_seeking.capitalize() in hair_color_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_color_seeking_options)

while True:
    hair_texture_seeking = input("Enter your partners desired hair texture, or type 'Unimportant': ")
    if hair_texture_seeking.capitalize() in hair_texture_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",hair_texture_seeking_options)

while True:
    eye_color_seeking = input("Enter your partners desired eye color, or type 'Unimportant': ")
    if eye_color_seeking.capitalize() in eye_color_seeking_options:
        break
    else:
        print("\nNot a Valid Input, Please Enter a Value From The Following Options:\n",eye_color_seeking_options)

while True:
    height_seeking = input("Enter your partners desired height (in inches, 5ft = 60in), or type 'Unimportant': ")
    if height_seeking.capitalize() == 'Unimportant':
        break
    else:
        try:
            if int(height_seeking) >= 48 and int(height_seeking) < 96:
                break
            else:
                print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96, or 'Unimportant'.\n")
        except ValueError:
            print("\nNot a Valid Input, Please Enter a Number of Inches Between 48 and 96, or 'Unimportant'.\n")

People.append({
    'Name': name,
    'Number': number,

    'Characteristic_Age': age.capitalize(),
    'Characteristic_Gender': gender.capitalize(),
    'Characteristic_Hair_color': hair_color.capitalize(),
    'Characteristic_Hair_Texture': hair_texture.capitalize(),
    'Characteristic_Eye_Color': eye_color.capitalize(),
    'Characteristic_Height': height.capitalize(),

    'Seeking_Age_Min': age_min_seeking.capitalize(),
    'Seeking_Age_Max': age_max_seeking.capitalize(),
    'Seeking_Gender': gender_seeking.capitalize(),
    'Seeking_Hair_Color': hair_color_seeking.capitalize(),
    'Seeking_Hair_Texture': hair_texture_seeking.capitalize(),
    'Seeking_Eye_Color': eye_color_seeking.capitalize(),
    'Seeking_Height': height_seeking.capitalize()
})


info = pd.read_csv('People.csv')
df = pd.DataFrame(People)
info_appended = info.append(df, ignore_index=True)
info_appended.to_csv('People.csv')

print("\nInformation Successfully Inputted! \n")

Enter your full name: lilly marco
Enter your contact phone number: 5188606181
Enter your age: 19
Enter your gender: female
Enter your hair color: brown
Enter your hair texture: curly
Enter your eye color: brown
Enter your height (in inches, 5ft = 60in): 62
Enter your partners desired MINumum age, or type 'Unimportant': 19
Enter your partners desired MAXimum age, or type 'Unimportant': 22
Enter your partners desired gender, or type 'Unimportant': male
Enter your partners desired hair color, or type 'Unimportant': unimportant
Enter your partners desired hair texture, or type 'Unimportant': unimportant
Enter your partners desired eye color, or type 'Unimportant': unimportant
Enter your partners desired height (in inches, 5ft = 60in), or type 'Unimportant': 70

Information Successfully Inputted!

In [150]:
profiles = pd.read_csv('People.csv')
profiles

,Unnamed: 0,Characteristic_Age,Characteristic_Eye_Color,Characteristic_Gender,Characteristic_Hair_Texture,Characteristic_Hair_color,Characteristic_Height,Name,Number,Number.1,Seeking_Age_Max,Seeking_Age_Min,Seeking_Eye_Color,Seeking_Gender,Seeking_Hair_Color,Seeking_Hair_Texture,Seeking_Height,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1
0,0,20,Brown,Male,Straight,Brown,72,Ian Orlando,0,8022384553,22,18,Unimportant,Female,Unimportant,Unimportant,69,0.0,0.0,0.0
1,1,20,Mixed,Female,Wavy,Brown,69,Sarah Crawford,1,8022384553,22,20,Brown,Male,Brown,Straight,72,1.0,1.0,1.0
2,2,21,Blue,Male,Straight,Blond,70,John smith,2,1234567899,21,17,Unimportant,Unimportant,Unimportant,Unimportant,70,2.0,2.0,2.0
3,3,22,Red,Male,Curly,Brown,55,bobby columbo,3,iorlando@syr.edu,21,20,Brown,Female,Brown,Unimportant,Unimportant,3.0,3.0,3.0
4,4,18,Blue,Male,Straight,Blue,66,joseph levit,4,2828082108312,19,18,Blue,Male,Blue,Straight,66,4.0,4.0,4.0
5,5,63,Blue,Female,Curly,Blond,64,princess dianna,5,6786786677,67,22,Gray,Male,Brown,Curly,66,5.0,5.0,5.0
6,6,23,Red,Male,Frizzy,Blond,70,jimmy mith,6,9292929,23,19,Brown,Female,White,Unimportant,70,6.0,6.0,6.0
7,7,20,Brown,Female,Straight,Brown,60,jennifer skulski,0,292929292,23,19,Unimportant,Male,Unimportant,Unimportant,78,7.0,7.0,7.0
8,8,24,Red,Female,Curly,Brown,65,colbert,202020202,NaN,Unimportant,Unimportant,Unimportant,Female,Unimportant,Curly,65,8.0,8.0,0.0
9,9,32,Amber,Male,Frizzy,Mixed,65,ronald,0202022-,NaN,43,19,Green,Female,Mixed,Curly,65,9.0,0.0,NaN
10,10,21,Blue,Female,Wavy,Black,69,Meredith Vondran,254112232,NaN,22,20,Unimportant,Male,Unimportant,Unimportant,Unimportant,10.0,NaN,NaN
11,11,19,Brown,Female,Curly,Brown,62,lilly marco,5188606181,NaN,22,19,Unimportant,Male,Unimportant,Unimportant,70,NaN,NaN,NaN

In [155]:
name = input("Enter your name: ")
person = profiles[ profiles['Name'].str.startswith(name)]
search = person['Name'].value_counts()
searchcount = 0
for people in search:
    searchcount = searchcount + 1

if searchcount == 1:
    print("Is your name", person['Name'][person['Unnamed: 0'].values[0]],"? (y/n) ")
    answer = input()
    if answer.capitalize() == 'Yes' or answer.capitalize() == 'Y':
        print("MAKING A MATCH...")
    elif answer.capitalize() == 'No' or answer.capitalize() == 'N':
        print("Please try again")
    else:
        print("Missunderstood input, please try again")
elif searchcount > 1:
    print("Multiple names found, please be more specific")
else:
    print("Name not found, please try again")

Enter your name: lil
Is your name lilly marco ? (y/n)
y
MAKING A MATCH...

In [156]:
person_gender = person['Characteristic_Gender'][person['Unnamed: 0'].values[0]]
person_gender_seeking = person['Seeking_Gender'][person['Unnamed: 0'].values[0]]

person_age = person['Characteristic_Age'][person['Unnamed: 0'].values[0]]
person_age_max_seeking = person['Seeking_Age_Max'][person['Unnamed: 0'].values[0]]
person_age_min_seeking = person['Seeking_Age_Min'][person['Unnamed: 0'].values[0]]

person_height_seeking = person['Seeking_Height'][person['Unnamed: 0'].values[0]]

gender_df = profiles[ (profiles['Seeking_Gender'] == person_gender) & (profiles['Characteristic_Gender'] == person_gender_seeking)]

number_gender = 0

for person in gender_df['Name'].value_counts():
    number_gender = number_gender + 1

if number_gender > 1:
    age_df = gender_df[ (gender_df['Characteristic_Age'] <= int(person_age_max_seeking)) & (gender_df['Characteristic_Age'] >= int(person_age_min_seeking))]
    number_age = 0
    
    for person2 in age_df['Name'].value_counts():
        number_age = number_age + 1

    if number_age > 1:
        height_df2 = pd.DataFrame(age_df['Characteristic_Height'], age_df['Unnamed: 0'])
        height_df3 = height_df2[ height_df2['Characteristic_Height'] == int(person_height_seeking)]

        try:
            final_number = height_df3.sample(1)
            final_number1 = final_number.index[0]
        except:
            final_number = height_df2.sample(1)
            final_number1 = final_number.index[0]
            
    elif number_age == 1:
        final_number1 = age_df.index[0]
    else:
        final_number = gender_df.sample(1)
        final_number1 = final_number.index[0]
elif number_gender == 1:
    final_number1 = gender_df.index[0]
else:
    final_number = profiles.sample(1)
    final_number1 = final_number.index[0]

In [157]:
match_df = profiles[ profiles['Unnamed: 0'] == final_number1]
name_match = match_df['Name'][final_number1]
number_match = match_df['Number.1'][final_number1]

print("You've matched with:",name_match + ". Their contact information is:",number_match)

You've matched with: bobby columbo. Their contact information is: iorlando@syr.edu